train:
  _target_: src.transforms.audio_pipeline.AudioPipeline
  feature_extractor:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
  wave_transforms: null
  spectrogram_transforms: null
inference:
  _target_: src.transforms.audio_pipeline.AudioPipeline
  feature_extractor:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
  wave_transforms: null
  spectrogram_transforms: null
